const products = [
  {
    _id: "1",
    name: "ダンスレッスン",
    image: "/images/dance_tanpatukeiyaku.png",
    description: "1時間のダンスレッスンをします！",
    contract_type: "単発契約",
    category: "dance",
    price: 2000,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "ボーカルレッスン",
    image: "/images/vocal_tanpatukeiyaku.png",
    description: "1時間のボーカルレッスンをします！",
    contract_type: "単発契約",
    category: "vocal",
    price: 2200,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "メイクレッスン",
    image: "/images/make_tanpatukeiyaku.png",
    description: "1時間のメイクレッスンをします！",
    contract_type: "単発契約",
    category: "make",
    price: 1800,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "食事管理方法伝授",
    image: "/images/shokujikanri_tanpatukeiyaku.png",
    description: "1時間で、食事管理についてのコツや疑問にお答えします！",
    contract_type: "単発契約",
    category: "others",
    price: 1500,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "週一ダンスレッスン",
    image: "/images/dance_tukikeiyaku.png",
    description: "週1で、ダンスのレッスンを行います！1回のレッスンは45分です！",
    contract_type: "月契約",
    category: "dance",
    price: 7000,
    rating: 4.5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "週一ボーカルレッスン",
    image: "/images/vocal_tukikeiyaku.png",
    description:
      "週1で、ボーカルのレッスンを行います！1回のレッスンは45分です！",
    contract_type: "月契約",
    category: "vocal",
    price: 7500,
    rating: 4,
    numReviews: 8,
  },
];

export default products;
